# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'Roots' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	# use_frameworks!
	rn_path = '../node_modules/react-native'
	rn_maps_path = '../node_modules/react-native-maps'

	# Pods for Roots
	pod 'Firebase/Core', '~> 5.11.0'
	pod 'Firebase/Firestore', '~> 5.11.0'
	pod 'React', path: rn_path, subspecs: [
		'Core',
		'CxxBridge',
		'DevSupport',
		'RCTActionSheet',
		'RCTAnimation',
		'RCTGeolocation',
		'RCTImage',
		'RCTLinkingIOS',
		'RCTNetwork',
		'RCTSettings',
		'RCTText',
		'RCTVibration',
		'RCTWebSocket',
	]
	pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
	pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
	pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
	pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
	pod 'Interactable', :path => '../node_modules/react-native-interactable'

	pod 'react-native-maps', path: rn_maps_path
	pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
	pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
	pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

	target 'Roots-tvOSTests' do
		inherit! :search_paths
		# Pods for testing
		pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

	end

	pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
	pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
	pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

	target 'RootsTests' do
		inherit! :search_paths
	end

end

target 'Roots-tvOS' do
end


post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == 'react-native-google-maps'
			target.build_configurations.each do |config|
				config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
			end
		end
		if target.name == "React"
			target.remove_from_project
		end
	end
end
